services:
  postgres-db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
     - db:/var/lib/postgresql/data

  # blog-backend:
  #   container_name: blog-backend
  #   build: .
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - postgres-db 
  #   env_file:
  #     - ./.env 

volumes:
  db: 